#!/usr/bin/env python3
"""Developer CLI for INSR configuration and registry inspection."""
from __future__ import annotations
import argparse, json, re, sys
from pathlib import Path
from insr_registry import targets_from_registry
ROOT = Path(__file__).resolve().parents[1]
SCHEMA_VERSION = "1.0"
ORCID_RE = re.compile(r"^\d{4}-\d{4}-\d{4}-\d{3}[0-9X]$")
KNOWN_THEMES = {p.stem for p in (ROOT / "themes").glob("*.tex")} | {"academic","clinical","medical","technical","minimal","presentation","accessible-high-contrast"}
KNOWN_FONTSETS = {"libertinus","inter","ibm-plex","system","noto-multilingual"}

def tex_escape(value: object) -> str:
    s = str(value)
    return (s.replace('\\', r'\textbackslash{}').replace('&', r'\&').replace('%', r'\%')
             .replace('$', r'\$').replace('#', r'\#').replace('_', r'\_')
             .replace('{', r'\{').replace('}', r'\}').replace('~', r'\textasciitilde{}')
             .replace('^', r'\textasciicircum{}'))

def validate_config(data: dict) -> list[str]:
    errors=[]
    allowed={"schema_version","project","build","design","typography","metadata"}
    for k in data:
        if k not in allowed: errors.append(f"unknown top-level field: {k}")
    if data.get("schema_version") != SCHEMA_VERSION: errors.append("schema_version must be 1.0")
    targets=targets_from_registry()
    preset=data.get("build",{}).get("preset")
    if preset and preset not in targets: errors.append(f"unknown build.preset: {preset}")
    theme=data.get("design",{}).get("theme")
    if theme and theme not in KNOWN_THEMES: errors.append(f"unknown design.theme: {theme}")
    fontset=data.get("typography",{}).get("fontset")
    if fontset and fontset not in KNOWN_FONTSETS: errors.append(f"unknown typography.fontset: {fontset}")
    for i,a in enumerate(data.get("metadata",{}).get("authors",[]) or []):
        orcid=a.get("orcid")
        if orcid and not ORCID_RE.match(orcid): errors.append(f"metadata.authors[{i}].orcid is malformed")
    return errors

def configure(args):
    data=json.loads(Path(args.config).read_text(encoding='utf-8'))
    errors=validate_config(data)
    if errors:
        for e in errors: print(e, file=sys.stderr)
        return 2
    lines=["% Generated by tools/insr_cli.py configure; do not edit by hand.","\\INSRConfigure{"]
    mapping=[("build/preset", data.get("build",{}).get("preset")),("document/language", data.get("project",{}).get("language")),("design/theme", data.get("design",{}).get("theme")),("typography/fontset", data.get("typography",{}).get("fontset")),("metadata/title", data.get("project",{}).get("title"))]
    kv=[(k,v) for k,v in mapping if v]
    for n,(k,v) in enumerate(kv): lines.append(f"  {k} = {tex_escape(v)}" + ("," if n < len(kv)-1 else ""))
    lines.append("}")
    md=data.get("metadata",{})
    if md.get("authors"):
        names="; ".join(tex_escape(a.get('name','')) for a in md['authors'])
        lines.append(f"\\INSRMetadata{{authors = {{{names}}}}}")
    out=Path(args.output); out.write_text("\n".join(lines)+"\n", encoding='utf-8')
    return 0

def main(argv=None):
    p=argparse.ArgumentParser(prog='insr')
    sub=p.add_subparsers(dest='cmd', required=True)
    c=sub.add_parser('configure'); c.add_argument('config'); c.add_argument('-o','--output', default='generated-insr-config.tex'); c.set_defaults(func=configure)
    for name in ['list-targets']:
        sp=sub.add_parser(name); sp.set_defaults(func=lambda a: (print('\n'.join(sorted(targets_from_registry()))),0)[1])
    args=p.parse_args(argv); return args.func(args)
if __name__=='__main__': raise SystemExit(main())
